#Requires -Version 5.1
<#
  Discovery adapter: auto-extract REAL behavior from a source solution/repo.
  Finds canvas app packages (.msapp, or *.zip exports containing one), unpacks them to Power Fx
  with `pac canvas unpack`, and scans screens for action formulas; finds Power Automate flow
  definition.json files (loose, embedded in app packages, or in flow export zips) and summarizes
  triggers + connector/Graph/HTTP actions. Writes a behavior-evidence.md so the reimagined app
  implements real behavior, not just a UI shell.

  Read-only against the source files. Requires `pac` (for canvas unpack).

  Usage:
    ./scripts/analyze-artifacts.ps1 -SourcePath workspaces/<pilot>/evidence/source-repository `
        -OutFile workspaces/<pilot>/generated/current-state/behavior-evidence.md
#>
param(
  [Parameter(Mandatory = $true)][string]$SourcePath,
  [string]$OutFile
)
$ErrorActionPreference = "Stop"
$src = (Resolve-Path $SourcePath).Path
if (-not $OutFile) { $OutFile = Join-Path $src "behavior-evidence.md" }
$tmp = Join-Path ([System.IO.Path]::GetTempPath()) ("analyze-" + [guid]::NewGuid().ToString("N").Substring(0, 8))
New-Item -ItemType Directory -Force -Path $tmp | Out-Null
function TempDir { Join-Path $tmp ([guid]::NewGuid().ToString("N").Substring(0, 8)) }

# --- Single expansion pass: expand every *.zip once, collect roots to scan ---
$scanRoots = New-Object System.Collections.Generic.List[string]
$scanRoots.Add($src)
Get-ChildItem -Recurse -Path $src -Filter *.zip -ErrorAction SilentlyContinue | ForEach-Object {
  $dest = TempDir
  try { Expand-Archive -Path $_.FullName -DestinationPath $dest -Force -ErrorAction Stop; $scanRoots.Add($dest) }
  catch { Write-Host "  [warn] could not expand $($_.Name): $($_.Exception.Message)" -ForegroundColor DarkYellow }
}

# collect artifacts across all roots
$msapps = @(); $defs = @(); $bots = @()
foreach ($root in $scanRoots) {
  $msapps += Get-ChildItem -Recurse -Path $root -Filter *.msapp -ErrorAction SilentlyContinue | ForEach-Object { $_.FullName }
  $defs   += Get-ChildItem -Recurse -Path $root -Filter definition.json -ErrorAction SilentlyContinue | ForEach-Object { $_.FullName }
  $bots   += Get-ChildItem -Recurse -Path $root -Filter bot.xml -ErrorAction SilentlyContinue | ForEach-Object { $_.FullName }
}
$msapps = $msapps | Sort-Object -Unique
$defs   = $defs   | Sort-Object -Unique
$bots   = $bots   | Sort-Object -Unique

$actionRegex = 'Patch\(|\.Run\(|Launch\(|Navigate\(|Set\(|UpdateContext|Collect\(|Remove\(|SubmitForm\(|ClearCollect\(|Notify\(|Office365|SharePoint|Outlook|Reset\('
$out = New-Object System.Collections.Generic.List[string]
$out.Add("# Behavior Evidence (auto-extracted)")
$out.Add("")
$out.Add("_Generated by scripts/analyze-artifacts.ps1 from $src._")
$out.Add("")

# --- Canvas apps ---
$out.Add("## Canvas apps")
if (-not $msapps) { $out.Add("_None found._"); $out.Add("") }
foreach ($m in $msapps) {
  $name = [System.IO.Path]::GetFileNameWithoutExtension($m)
  $out.Add("### $name")
  $srcDir = TempDir
  try { pac canvas unpack --msapp $m --sources $srcDir 2>&1 | Out-Null }
  catch { $out.Add("_unpack failed: $($_.Exception.Message)_"); $out.Add(""); continue }
  $allScreens = Get-ChildItem -Recurse -Path $srcDir -Include *.fx.yaml, *.pa.yaml -ErrorAction SilentlyContinue |
    Where-Object { $_.Name -notmatch '^App\.' }
  # Prefer the current .fx.yaml; only include a legacy .pa.yaml if no .fx.yaml exists for that screen.
  $fxBases = @{}
  foreach ($f in ($allScreens | Where-Object { $_.Name -like '*.fx.yaml' })) { $fxBases[($f.Name -replace '\.fx\.yaml$', '')] = $true }
  $screens = $allScreens | Where-Object {
    if ($_.Name -like '*.fx.yaml') { $true } else { -not $fxBases[($_.Name -replace '\.pa\.yaml$', '')] }
  }
  foreach ($s in $screens) {
    $hits = Select-String -Path $s.FullName -Pattern $actionRegex -ErrorAction SilentlyContinue |
      ForEach-Object { $_.Line.Trim() } | Where-Object { $_ -match '=' } | Select-Object -Unique
    if ($hits) {
      $screenName = ($s.Name -replace '\.(fx|pa)\.yaml$', '')
      $out.Add("- **$screenName**")
      foreach ($h in ($hits | Select-Object -First 20)) {
        $clean = ($h -replace '\s+', ' '); if ($clean.Length -gt 200) { $clean = $clean.Substring(0, 200) + " ..." }
        $out.Add("  - ``$clean``")
      }
    }
  }
  $out.Add("")
}

# --- Dataverse tables (schema from solution customizations.xml) ---
$out.Add("## Dataverse tables")
$custFiles = @()
foreach ($root in $scanRoots) { $custFiles += Get-ChildItem -Recurse -Path $root -Filter customizations.xml -ErrorAction SilentlyContinue | ForEach-Object { $_.FullName } }
$custFiles = $custFiles | Sort-Object -Unique
$tableCount = 0
foreach ($cf in $custFiles) {
  try { [xml]$cx = Get-Content -Raw -Path $cf -ErrorAction Stop } catch { continue }
  foreach ($ent in $cx.SelectNodes('//Entity')) {
    $nameNode = $ent.SelectSingleNode('Name')
    if (-not $nameNode) { continue }
    $ename = $nameNode.InnerText.Trim()
    if (-not $ename) { continue }
    $prefix = (($ename -split '_')[0]).ToLower()
    $cols = @()
    foreach ($a in $ent.SelectNodes('.//attribute')) {
      $pn = $a.GetAttribute('PhysicalName')
      if (-not $pn) { continue }
      if (-not $pn.ToLower().StartsWith($prefix + '_')) { continue }
      $tn = $a.SelectSingleNode('Type'); $t = if ($tn) { $tn.InnerText.Trim() } else { '?' }
      $fn = $a.SelectSingleNode('Format'); $fmt = if ($fn) { $fn.InnerText.Trim() } else { '' }
      $desc = if ($fmt -and @('none', '') -notcontains $fmt) { "$t/$fmt" } else { $t }
      $cols += "$pn ($desc)"
    }
    if ($cols.Count -gt 0) {
      $tableCount++
      $out.Add("### $ename")
      foreach ($c in ($cols | Sort-Object -Unique)) { $out.Add("- $c") }
      $out.Add("**Recreate every column above in the target** (including image/file/choice/lookup) — dropping one is a regression, not a reimagining.")
      $out.Add("")
    }
  }
}
if ($tableCount -eq 0) { $out.Add("_No solution customizations.xml with custom tables found (columns may be defined elsewhere)._"); $out.Add("") }

# --- Copilot Studio agents (bots) ---
$out.Add("## Copilot Studio agents")
if (-not $bots) { $out.Add("_None found._"); $out.Add("") }
else {
  $seenBots = @{}
  foreach ($b in $bots) {
    $botDir = Split-Path $b -Parent
    $schemaName = Split-Path $botDir -Leaf
    if ($seenBots[$schemaName]) { continue } else { $seenBots[$schemaName] = $true }
    $display = $schemaName
    $cfg = Join-Path $botDir "configuration.json"
    if (Test-Path $cfg) {
      try {
        $c = Get-Content $cfg -Raw | ConvertFrom-Json
        if ($c.displayName) { $display = $c.displayName } elseif ($c.name) { $display = $c.name }
      } catch { }
    }
    $out.Add("### $display")
    $out.Add("- Schema name: ``$schemaName``")
    # Component inventory (topics / dialogs / actions) if present alongside the bot
    $components = Get-ChildItem -Recurse -Path $botDir -Include *.json, *.yaml, *.yml -ErrorAction SilentlyContinue |
      Where-Object { $_.Name -ne 'configuration.json' }
    if ($components) { $out.Add("- Component files: $($components.Count)") }
    $out.Add("- **Deep discovery:** route topics, actions, knowledge, and connected agents to the Copilot Studio specialists (Advisor/Author); this adapter only inventories the agent so it is never dropped.")
    $out.Add("")
  }
}

# --- Flows ---
$out.Add("## Power Automate flows")
if (-not $defs) { $out.Add("_None found._"); $out.Add("") }
$seen = @{}
foreach ($f in $defs) {
  try { $j = Get-Content $f -Raw | ConvertFrom-Json } catch { continue }
  $def = if ($j.properties.definition) { $j.properties.definition } elseif ($j.definition) { $j.definition } else { $j }
  if (-not ($def.triggers -or $def.actions)) { continue }
  $disp = $j.properties.displayName
  if (-not $disp) { $disp = $def.displayName }
  if (-not $disp) { $disp = Split-Path (Split-Path $f -Parent) -Leaf }
  if ($seen[$disp]) { continue } else { $seen[$disp] = $true }
  $out.Add("### $disp")
  if ($def.triggers) { foreach ($t in $def.triggers.PSObject.Properties) { $out.Add("- Trigger: **$($t.Name)** ($($t.Value.type))") } }
  if ($def.actions) {
    foreach ($a in $def.actions.PSObject.Properties) {
      $op = $a.Value.metadata.flowSystemMetadata.swaggerOperationId
      $uri = $a.Value.inputs.uri
      $detail = @($a.Value.type, $op, $uri) | Where-Object { $_ }
      $out.Add("  - **$($a.Name)** - $([string]::Join(' | ', $detail))")
    }
  }
  $out.Add("")
}

Set-Content -Path $OutFile -Value ($out -join "`r`n") -Encoding UTF8
Remove-Item -Recurse -Force $tmp -ErrorAction SilentlyContinue
Write-Host "[OK] behavior evidence -> $OutFile" -ForegroundColor Green
Write-Host "     Canvas apps: $($msapps.Count)   Dataverse tables: $tableCount   Copilot Studio agents: $($bots.Count)   Flow definitions: $($defs.Count)" -ForegroundColor DarkGray
